sudo: required

services:
  - docker

script:
  - docker build -t nifi .
  - docker run -d --name nifi -e DISABLE_SSL=true nifi
  - sleep 84
  - docker logs nifi
  - docker exec nifi /bin/sh -c "curl -f localhost:80/nifi/"
